#!/bin/sh
set -e

# Tag to allow some debhelper commands to inject relevant code


if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    # Remove vendor logos alternative, all slaves get removed automatically
    update-alternatives --remove \
            vendor-logos \
            /usr/share/desktop-base/vanilla-logos
fi
