#!/bin/sh
set -e

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ]; then
    # Vendor logo alternative
    mkdir -p /usr/share/images/vendor-logo || true
    echo "Setting up vendor-logo alternative"
    update-alternatives --install \
            /usr/share/images/vendor-logos \
            vendor-logos \
            /usr/share/desktop-base/vanilla-logos 50 \
            --slave /usr/share/icons/vendor/64x64/emblems/emblem-vendor.png \
                emblem-vendor-64 \
                /usr/share/icons/desktop-base/64x64/emblems/emblem-vanilla.png \
            --slave /usr/share/icons/vendor/128x128/emblems/emblem-vendor.png \
                emblem-vendor-128 \
                /usr/share/icons/desktop-base/128x128/emblems/emblem-vanilla.png \
            --slave /usr/share/icons/vendor/256x256/emblems/emblem-vendor.png \
                emblem-vendor-256 \
                /usr/share/icons/desktop-base/256x256/emblems/emblem-vanilla.png \
            --slave /usr/share/icons/vendor/scalable/emblems/emblem-vendor.svg \
                emblem-vendor-scalable \
                /usr/share/icons/desktop-base/scalable/emblems/emblem-vanilla.svg \
            --slave /usr/share/icons/vendor/64x64/emblems/emblem-vendor-symbolic.png \
                emblem-vendor-symbolic-64 \
                /usr/share/icons/desktop-base/64x64/emblems/emblem-vanilla-symbolic.png \
            --slave /usr/share/icons/vendor/128x128/emblems/emblem-vendor-symbolic.png \
                emblem-vendor-symbolic-128 \
                /usr/share/icons/desktop-base/128x128/emblems/emblem-vanilla-symbolic.png \
            --slave /usr/share/icons/vendor/256x256/emblems/emblem-vendor-symbolic.png \
                emblem-vendor-symbolic-256 \
                /usr/share/icons/desktop-base/256x256/emblems/emblem-vanilla-symbolic.png \
            --slave /usr/share/icons/vendor/scalable/emblems/emblem-vendor-symbolic.svg \
                emblem-vendor-symbolic-scalable \
                /usr/share/icons/desktop-base/scalable/emblems/emblem-vanilla-symbolic.svg \
            --slave /usr/share/icons/vendor/64x64/emblems/emblem-vendor-white.png \
                emblem-vendor-white-64 \
                /usr/share/icons/desktop-base/64x64/emblems/emblem-vanilla-white.png \
            --slave /usr/share/icons/vendor/128x128/emblems/emblem-vendor-white.png \
                emblem-vendor-white-128 \
                /usr/share/icons/desktop-base/128x128/emblems/emblem-vanilla-white.png \
            --slave /usr/share/icons/vendor/256x256/emblems/emblem-vendor-white.png \
                emblem-vendor-white-256 \
                /usr/share/icons/desktop-base/256x256/emblems/emblem-vanilla-white.png \
            --slave /usr/share/icons/vendor/scalable/emblems/emblem-vendor-white.svg \
                emblem-vendor-white-scalable \
                /usr/share/icons/desktop-base/scalable/emblems/emblem-vanilla-white.svg \
            --force
fi
